In [ ]:
import numpy as np

# Temperatures from 03 sensors over 05 days
sensor_temps=np.array([
    [72,70,71], #Day 1
    [75,73,74], #Day 2
    [68,67,69], #Day 3
    [71,70,72], #Day 4
    [74,72,73]  #Day 5
])

print(sensor_temps)
print(f"shape:{sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
shape:(5, 3)


In [ ]:
import numpy as np
# Array of Zeros(5*3)
Zeros=np.zeros((5,3))
print(Zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [ ]:
arr=np.array([1.5,2.7,3.2])
print(arr.dtype)

float64


In [ ]:
arr=np.array([1,2,3])
print(arr.itemsize)


8


In [ ]:
#Soil PH readings(3 fields * 4 samples)
ph_levels=np.array([
    [6.5,6.8,6.3,6.7],
    [7.1,7.0,6.9,7.2],
    [6.2,6.4,6.1,6.3]
])
#Single element: row 1, column 2
print(ph_levels[1,2])

6.9


In [1]:

import numpy as np

# === CREATING ARRAYS ===
print("=== Creating NumPy Arrays ===")

# From list
yields = np.array([2500, 2800, 3100, 2900, 2700])
print(f"Yields: {yields}")
print(f"Type: {type(yields)}")

# Using arange (like range, but for arrays)
plot_numbers = np.arange(1, 6)
print(f"Plots: {plot_numbers}")

# Using linspace (evenly spaced)
temperatures = np.linspace(20, 35, 5)
print(f"Temperature range: {temperatures}")

# 2D Array (matrix) - farm grid
farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])
print(f"\nFarm Grid:\n{farm_grid}")
print(f"Shape: {farm_grid.shape}")  # 3 rows, 3 columns

# === INDEXING AND SLICING ===
print("\n=== Indexing and Slicing ===")

# Access elements
print(f"First yield: {yields[0]}")
print(f"Last yield: {yields[-1]}")
print(f"First 3 yields: {yields[:3]}")

# 2D indexing
print(f"Center plot yield: {farm_grid[1, 1]}")
print(f"First row: {farm_grid[0]}")
print(f"Last column: {farm_grid[:, -1]}")

# === ARRAY OPERATIONS ===
print("\n=== Array Operations ===")

# Math on entire arrays (vectorized!)
yields_tons = yields / 1000
print(f"Yields in tons: {yields_tons}")

# Bonus calculation
bonus = np.where(yields > 2800, 500, 0)
print(f"Bonus per plot: {bonus}")

# Statistics
print(f"\nTotal yield: {np.sum(yields)} kg")
print(f"Average: {np.mean(yields):.0f} kg")
print(f"Std Dev: {np.std(yields):.0f} kg")
print(f"Max: {np.max(yields)} kg, Min: {np.min(yields)} kg")

# Boolean filtering
high_yield_plots = yields[yields > 2700]
print(f"High yield plots (>2700): {high_yield_plots}")


=== Creating NumPy Arrays ===
Yields: [2500 2800 3100 2900 2700]
Type: <class 'numpy.ndarray'>
Plots: [1 2 3 4 5]
Temperature range: [20.   23.75 27.5  31.25 35.  ]

Farm Grid:
[[2500 2600 2700]
 [2800 2900 3000]
 [2400 2500 2600]]
Shape: (3, 3)

=== Indexing and Slicing ===
First yield: 2500
Last yield: 2700
First 3 yields: [2500 2800 3100]
Center plot yield: 2900
First row: [2500 2600 2700]
Last column: [2700 3000 2600]

=== Array Operations ===
Yields in tons: [2.5 2.8 3.1 2.9 2.7]
Bonus per plot: [  0   0 500 500   0]

Total yield: 14000 kg
Average: 2800 kg
Std Dev: 200 kg
Max: 3100 kg, Min: 2500 kg
High yield plots (>2700): [2800 3100 2900]


In [3]:

import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)
