In [70]:
#vector operation
import numpy as np
a=np.array([1,6,5,8,4])
b=np.array([5,6,9,2,1])
print(a+b)

[ 6 12 14 10  5]


In [71]:
#martrices operation
x = np.array([
    [3,5,6],
    [3,6,3],
    [7,4,3],
    [4,7,9]
])
print(x)

[[3 5 6]
 [3 6 3]
 [7 4 3]
 [4 7 9]]


In [72]:
#dot product
result = np.dot([6,7,4],[4,2,9])
print(result)

74


In [73]:
#handling uncertainity
import random
outcomes=["spam","not spam"]
print(random.choice(outcomes))

spam


In [74]:
#mean
import numpy as np
a=np.array([1,6,5,8,4])
print(np.mean(a))


4.8


In [75]:
#normal distribution(bellcurve)
w=7
ir=0.6
for i in range(10):
    w=w*ir
    print(w)


4.2
2.52
1.512
0.9072
0.54432
0.326592
0.1959552
0.11757311999999999
0.070543872
0.042326323199999995


In [77]:
file=open("attendance.txt","w")
file.write("attendance:07th January, 2025")
file.write("\n Names of studentd present today:-")
file.write("\n Manasa, Diksha,Sneha,Dattu kumar")
file.write("\n Names of Students absent today:-")
file.write("\n Ravi")
file.close()

In [78]:
file=open("attendance.txt","r")
content=file.read()
print(content)
file.close()

attendance:07th January, 2025
 Names of studentd present today:-
 Manasa, Diksha,Sneha,Dattu kumar
 Names of Students absent today:-
 Ravi


In [ ]:
file=open("attendance.txt","r")
content=file.read()
print(content)
file.close()

In [ ]:
file=open("Expenses.txt","w")
file.write("Expenses:07th January, 2025")
file.write("\n Dairy milk - 10 Rs")
file.write("\n milk - 22 Rs")
file.write("\n Bread - 12 Rs")
file.write("\n coffee- 12 Rs")
file.write("\n Tea - 10 Rs")
file.close()

In [ ]:
file=open("Expenses.txt","r")
content=file.read()
print(content)
file.close()